-- ═══════════════════════════════════════════════════════════════════════════
-- Seed: 13 Verified Global Scholarships (August 2026 Cycle)
-- Run this in Supabase Dashboard → SQL Editor with service_role key
-- ═══════════════════════════════════════════════════════════════════════════

-- 1. Knight-Hennessy Scholars 2027 (Stanford University)
INSERT INTO scholarships (
  id, slug, name, provider, host_institution, countries, degree_levels,
  fields_of_study, funding_type, amount, deadline, opens_at,
  description, eligibility, required_documents, apply_url, source_url,
  published, verified, verified_at, verified_by, pipeline_source,
  host_region, host_country, urgency, sponsor_type, category,
  no_ielts, requires_leadership, is_intra_african,
  instruction_language, min_gpa_normalised,
  age_limit_masters, age_limit_phd, work_experience_required,
  requires_research, requires_publications, requires_community,
  targets_financial_need, targets_first_generation, targets_rural_origin,
  targets_ldc_countries, min_english_score, min_english_test_type
) VALUES (
  'schol-kh-2027',
  'knight-hennessy-scholars-2027',
  'Knight-Hennessy Scholars 2027',
  'Stanford University',
  'Stanford University',
  '[]',
  '["Masters", "PhD"]',
  '[]',
  'Full',
  'Full funding, living stipend, academic expenses, travel',
  '2026-10-06',
  NULL,
  'A multidisciplinary, multicultural graduate scholarship program spanning all seven schools at Stanford University. The 2026 cohort represents 31 countries and 45 graduate degree programs.',
  'Must have earned a bachelor''s degree in 2020 or later. Must apply and be selected for admission to a full-time Stanford graduate degree program. Requires separate application to Stanford by December 1, 2026.',
  '["Online Application", "Resume", "Transcripts & Test Scores", "Recommendation Letters", "Short Answers & Essay"]',
  'https://apply.knight-hennessy.stanford.edu/register/',
  'https://knight-hennessy.stanford.edu/admission',
  true, true, now(), 'manual', 'pipeline',
  'North America', '["USA"]'::jsonb, 'Normal', 'University', 'Full Scholarships Open Now',
  false, true, false,
  'English', NULL,
  NULL, NULL, NULL,
  NULL, NULL, NULL,
  NULL, NULL, NULL,
  NULL, NULL, NULL
);

-- 2. Schwarzman Scholars Class of 2027-2028
INSERT INTO scholarships (
  id, name, provider, host_institution, countries, degree_levels,
  fields_of_study, funding_type, amount, deadline, opens_at,
  description, eligibility, required_documents, apply_url, source_url,
  published, verified, verified_at, verified_by, pipeline_source,
  host_region, host_country, urgency, sponsor_type, category,
  no_ielts, requires_leadership, is_intra_african,
  instruction_language, min_gpa_normalised,
  age_limit_masters, age_limit_phd, work_experience_required,
  requires_research, requires_publications, requires_community,
  targets_financial_need, targets_first_generation, targets_rural_origin,
  targets_ldc_countries, min_english_score, min_english_test_type
) VALUES (
  'schol-schwarzman-2027',
  'schwarzman-scholars-2027-2028',
  'Schwarzman Scholars Class of 2027-2028',
  'Schwarzman Scholars',
  'Schwarzman College, Tsinghua University',
  '[]',
  '["Masters"]',
  '[]',
  'Full',
  'Tuition & Fees, Room & Board, In-Country Study Tour, Travel To and From Beijing, Health Insurance, Stipend for Personal Expenses',
  '2026-09-09',
  NULL,
  'A one-year, fully-funded master''s degree program in global affairs at Schwarzman College, Tsinghua University in Beijing, China. Focused on leadership and global affairs.',
  'Must have an undergraduate degree by August 1, 2027. Candidates must be at least 18 but not yet 29 years of age as of August 1 of their enrollment year. English proficiency waived for applicants who studied in English for at least two years.',
  '["Resume/Curriculum Vitae", "2 Essays (Leadership Essay and Statement of Purpose)", "Transcript/Academic Records", "3 Letters of Recommendation", "Video Introduction"]',
  'https://connect.schwarzmanscholars.org/apply/',
  'https://www.schwarzmanscholars.org/admissions/',
  true, true, now(), 'manual', 'pipeline',
  'Asia', '["China"]'::jsonb, 'Urgent', 'Foundation', 'Full Scholarships Open Now',
  true, true, false,
  'English', NULL,
  28, NULL, NULL,
  NULL, NULL, NULL,
  NULL, NULL, NULL,
  NULL, NULL, NULL
);

-- 3. Swiss Government Excellence Scholarships 2027-2028
INSERT INTO scholarships (
  id, name, provider, host_institution, countries, degree_levels,
  fields_of_study, funding_type, amount, deadline, opens_at,
  description, eligibility, required_documents, apply_url, source_url,
  published, verified, verified_at, verified_by, pipeline_source,
  host_region, host_country, urgency, sponsor_type, category,
  no_ielts, requires_leadership, is_intra_african,
  instruction_language, min_gpa_normalised,
  age_limit_masters, age_limit_phd, work_experience_required,
  requires_research, requires_publications, requires_community,
  targets_financial_need, targets_first_generation, targets_rural_origin,
  targets_ldc_countries, min_english_score, min_english_test_type
) VALUES (
  'schol-swiss-gov-2027',
  'swiss-government-excellence-scholarships-2027-2028',
  'Swiss Government Excellence Scholarships 2027-2028',
  'Swiss Confederation (FCS)',
  'Swiss cantonal universities, federal institutes of technology, and research institutes',
  '[]',
  '["PhD", "Masters", "Postdoctoral"]',
  '[]',
  'Full',
  'CHF 2,450/month',
  NULL,
  '2026-08-20',
  'Government Excellence Scholarships to encourage international exchange and research cooperation between Switzerland and over 180 other countries. Available to 183 countries including African nations.',
  'Highly qualified early-career researchers from all academic fields pursuing a PhD or research. Date of birth after 31 December 1991. Must secure a letter of support from an academic supervisor in Switzerland.',
  '["Complete CV", "Letter of motivation", "Detailed research plan", "Letter of support from an academic supervisor in Switzerland (including short CV)"]',
  'https://www.sbfi.admin.ch/en/swiss-government-excellence-scholarships',
  'https://www.sbfi.admin.ch/en/swiss-government-excellence-scholarships',
  true, true, now(), 'manual', 'pipeline',
  'Europe', '["Switzerland"]'::jsonb, 'Normal', 'Government', 'Full Scholarships Open Now',
  false, false, false,
  'English', NULL,
  34, 34, NULL,
  true, NULL, NULL,
  NULL, NULL, NULL,
  NULL, NULL, NULL
);

-- 4. Lester B. Pearson International Scholarship 2027
INSERT INTO scholarships (
  id, name, provider, host_institution, countries, degree_levels,
  fields_of_study, funding_type, amount, deadline, opens_at,
  description, eligibility, required_documents, apply_url, source_url,
  published, verified, verified_at, verified_by, pipeline_source,
  host_region, host_country, urgency, sponsor_type, category,
  no_ielts, requires_leadership, is_intra_african,
  instruction_language, min_gpa_normalised,
  age_limit_masters, age_limit_phd, work_experience_required,
  requires_research, requires_publications, requires_community,
  targets_financial_need, targets_first_generation, targets_rural_origin,
  targets_ldc_countries, min_english_score, min_english_test_type
) VALUES (
  'schol-pearson-2027',
  'lester-b-pearson-international-scholarship-2027',
  'Lester B. Pearson International Scholarship 2027',
  'University of Toronto',
  'University of Toronto',
  '[]',
  '["Bachelors"]',
  '[]',
  'Full',
  'Tuition, books, incidental fees, and full residence support for four years',
  '2026-11-06',
  NULL,
  'The Lester B. Pearson International Scholarships is the largest scholarship program for international students in Canada, awarded to outstanding leaders.',
  'Must be an international student requiring a study permit; enrolled in final year of senior secondary school in 2026/2027 or graduated no earlier than June 2026; nominated by high school.',
  '[]',
  'https://future.utoronto.ca/pearson-scholarships',
  'https://future.utoronto.ca/pearson-scholarships',
  true, true, now(), 'manual', 'pipeline',
  'North America', '["Canada"]'::jsonb, 'Normal', 'University', 'Full Scholarships Open Now',
  false, true, false,
  'English', NULL,
  NULL, NULL, NULL,
  NULL, NULL, NULL,
  NULL, NULL, NULL,
  NULL, NULL, NULL
);

-- 5. Singapore International Graduate Award (SINGA)
INSERT INTO scholarships (
  id, name, provider, host_institution, countries, degree_levels,
  fields_of_study, funding_type, amount, deadline, opens_at,
  description, eligibility, required_documents, apply_url, source_url,
  published, verified, verified_at, verified_by, pipeline_source,
  host_region, host_country, urgency, sponsor_type, category,
  no_ielts, requires_leadership, is_intra_african,
  instruction_language, min_gpa_normalised,
  age_limit_masters, age_limit_phd, work_experience_required,
  requires_research, requires_publications, requires_community,
  targets_financial_need, targets_first_generation, targets_rural_origin,
  targets_ldc_countries, min_english_score, min_english_test_type
) VALUES (
  'schol-singa-2026',
  'singapore-international-graduate-award-singa',
  'Singapore International Graduate Award (SINGA)',
  'A*STAR, NTU, NUS, SUTD, SMU',
  'Singapore Autonomous Universities',
  '[]',
  '["PhD"]',
  '[]',
  'Full',
  'Tuition fees, S$2000-S$2200/month stipend, one-time settling-in and airfare grants',
  '2026-10-10',
  NULL,
  'A joint collaboration to attract international students seeking admission as a full-time student for a PhD by research in Singapore. Funding increases after qualifying exam.',
  'Available to all international students with a relevant Bachelor''s or Master''s degree seeking admission as a full-time student for a PhD by research.',
  '["GRE test scores (general test)", "TOEFL or IELTS"]',
  'https://www.a-star.edu.sg/ime/careers',
  'https://www.ntu.edu.sg/spms/admissions/grad/scholarships',
  true, true, now(), 'manual', 'pipeline',
  'Asia', '["Singapore"]'::jsonb, 'Normal', 'Government', 'Full Scholarships Open Now',
  true, false, false,
  'English', NULL,
  NULL, NULL, NULL,
  true, NULL, NULL,
  NULL, NULL, NULL,
  NULL, 6.5, 'IELTS'
);

-- 6. Chevening Scholarships 2027-2028
INSERT INTO scholarships (
  id, name, provider, host_institution, countries, degree_levels,
  fields_of_study, funding_type, amount, deadline, opens_at,
  description, eligibility, required_documents, apply_url, source_url,
  published, verified, verified_at, verified_by, pipeline_source,
  host_region, host_country, urgency, sponsor_type, category,
  no_ielts, requires_leadership, is_intra_african,
  instruction_language, min_gpa_normalised,
  age_limit_masters, age_limit_phd, work_experience_required,
  requires_research, requires_publications, requires_community,
  targets_financial_need, targets_first_generation, targets_rural_origin,
  targets_ldc_countries, min_english_score, min_english_test_type
) VALUES (
  'schol-chevening-2027',
  'chevening-scholarships-2027-2028',
  'Chevening Scholarships 2027-2028',
  'Foreign, Commonwealth and Development Office',
  'Eligible UK Universities',
  '[]',
  '["Masters"]',
  '[]',
  'Full',
  'Prestigious international scholarships programme funding (partner awards available)',
  '2026-10-06',
  NULL,
  'Chevening is the UK Government''s prestigious international scholarships programme offering exceptional future leaders the opportunity to further their education in the UK. Covers 140+ countries including Kenya, Somalia, South Africa.',
  'Must meet eligibility criteria, including leadership potential, and apply for an eligible one-year taught master''s course in the UK.',
  '[]',
  'https://www.chevening.org/scholarship/kenya/',
  'https://www.chevening.org/scholarship/kenya/',
  true, true, now(), 'manual', 'pipeline',
  'Europe', '["UK"]'::jsonb, 'Normal', 'Government', 'Full Scholarships Open Now',
  false, true, false,
  'English', NULL,
  NULL, NULL, NULL,
  NULL, NULL, NULL,
  NULL, NULL, NULL,
  NULL, NULL, NULL
);

-- 7. Gates Cambridge Scholarship 2027
INSERT INTO scholarships (
  id, name, provider, host_institution, countries, degree_levels,
  fields_of_study, funding_type, amount, deadline, opens_at,
  description, eligibility, required_documents, apply_url, source_url,
  published, verified, verified_at, verified_by, pipeline_source,
  host_region, host_country, urgency, sponsor_type, category,
  no_ielts, requires_leadership, is_intra_african,
  instruction_language, min_gpa_normalised,
  age_limit_masters, age_limit_phd, work_experience_required,
  requires_research, requires_publications, requires_community,
  targets_financial_need, targets_first_generation, targets_rural_origin,
  targets_ldc_countries, min_english_score, min_english_test_type
) VALUES (
  'schol-gates-cam-2027',
  'gates-cambridge-scholarship-2027',
  'Gates Cambridge Scholarship 2027',
  'Gates Cambridge Trust',
  'University of Cambridge',
  '[]',
  '["PhD", "Masters"]',
  '[]',
  'Full',
  'Full-cost scholarship',
  NULL,
  NULL,
  'An international scholarship programme at the University of Cambridge established by the Bill & Melinda Gates Foundation. Expected to open September 2026.',
  'Citizen of any country outside the UK applying for PhD, MLitt, or a one-year postgraduate course. Must show academic excellence, reasons for choice of course, a commitment to improving the lives of others, and a capacity for leadership.',
  '["Research proposal (PhD only)", "Gates Cambridge reference", "Two academic references"]',
  'https://www.gatescambridge.org/apply/',
  'https://www.gatescambridge.org/apply/timeline/',
  true, true, now(), 'manual', 'pipeline',
  'Europe', '["UK"]'::jsonb, 'Opens Soon', 'Foundation', 'Full Scholarships Opening Soon',
  false, true, false,
  'English', NULL,
  NULL, NULL, NULL,
  NULL, NULL, true,
  false, NULL, NULL,
  NULL, NULL, NULL
);

-- 8. Commonwealth Master's Scholarships 2027/28
INSERT INTO scholarships (
  id, name, provider, host_institution, countries, degree_levels,
  fields_of_study, funding_type, amount, deadline, opens_at,
  description, eligibility, required_documents, apply_url, source_url,
  published, verified, verified_at, verified_by, pipeline_source,
  host_region, host_country, urgency, sponsor_type, category,
  no_ielts, requires_leadership, is_intra_african,
  instruction_language, min_gpa_normalised,
  age_limit_masters, age_limit_phd, work_experience_required,
  requires_research, requires_publications, requires_community,
  targets_financial_need, targets_first_generation, targets_rural_origin,
  targets_ldc_countries, min_english_score, min_english_test_type
) VALUES (
  'schol-commonwealth-2027',
  'commonwealth-masters-scholarships-2027-28',
  'Commonwealth Master''s Scholarships 2027/28',
  'Commonwealth Scholarship Commission',
  'UK Universities',
  '[]',
  '["Masters"]',
  '[]',
  'Full',
  'Approved tuition fees, stipend (living allowance), approved airfare, study travel grant',
  '2026-10-20',
  '2026-09-08',
  'Scholarships for candidates from eligible Commonwealth countries to undertake full-time taught Master''s study at a UK university. Targets financial need.',
  'Citizen of or granted refugee status by an eligible Commonwealth country. Hold a first degree of at least upper second-class (2:1) standard by September 2027. Unable to afford to study in the UK without this scholarship.',
  '["Copy of valid passport or national ID", "Full university transcripts", "References on institution letterhead"]',
  'https://cscuk.fcdo.gov.uk/scholarships/commonwealth-masters-scholarships/',
  'https://cscuk.fcdo.gov.uk/scholarships/commonwealth-masters-scholarships/',
  true, true, now(), 'manual', 'pipeline',
  'Europe', '["UK"]'::jsonb, 'Opens Soon', 'Government', 'Full Scholarships Opening Soon',
  false, false, false,
  'English', NULL,
  NULL, NULL, NULL,
  NULL, NULL, NULL,
  true, NULL, NULL,
  NULL, NULL, NULL
);

-- 9. ETH Zurich Excellence Scholarship (ESOP)
INSERT INTO scholarships (
  id, name, provider, host_institution, countries, degree_levels,
  fields_of_study, funding_type, amount, deadline, opens_at,
  description, eligibility, required_documents, apply_url, source_url,
  published, verified, verified_at, verified_by, pipeline_source,
  host_region, host_country, urgency, sponsor_type, category,
  no_ielts, requires_leadership, is_intra_african,
  instruction_language, min_gpa_normalised,
  age_limit_masters, age_limit_phd, work_experience_required,
  requires_research, requires_publications, requires_community,
  targets_financial_need, targets_first_generation, targets_rural_origin,
  targets_ldc_countries, min_english_score, min_english_test_type
) VALUES (
  'schol-eth-esop-2026',
  'eth-zurich-excellence-scholarship-esop',
  'ETH Zurich Excellence Scholarship (ESOP)',
  'ETH Foundation',
  'ETH Zurich',
  '[]',
  '["Masters"]',
  '[]',
  'Full',
  'CHF 13,500 per semester (from HS27) + tuition fee waiver',
  '2026-11-30',
  '2026-11-01',
  'Supports excellent students with a scholarship, mentorship and a network. Covers full study and living costs during the Master''s degree course.',
  'Very good result in Bachelor''s degree programme (top 10% of Bachelor''s degree programme = grade A).',
  '["Pre-proposal for master thesis", "Two reference letters from professors"]',
  'https://ethz.ch/students/en/studies/financial/scholarships/excellencescholarship.html',
  'https://ethz.ch/students/en/studies/financial/scholarships/excellencescholarship.html',
  true, true, now(), 'manual', 'pipeline',
  'Europe', '["Switzerland"]'::jsonb, 'Opens Soon', 'University', 'Full Scholarships Opening Soon',
  false, false, false,
  'English', NULL,
  NULL, NULL, NULL,
  true, NULL, NULL,
  NULL, NULL, NULL,
  NULL, NULL, NULL
);

-- 10. Imperial College President's PhD Scholarships
INSERT INTO scholarships (
  id, name, provider, host_institution, countries, degree_levels,
  fields_of_study, funding_type, amount, deadline, opens_at,
  description, eligibility, required_documents, apply_url, source_url,
  published, verified, verified_at, verified_by, pipeline_source,
  host_region, host_country, urgency, sponsor_type, category,
  no_ielts, requires_leadership, is_intra_african,
  instruction_language, min_gpa_normalised,
  age_limit_masters, age_limit_phd, work_experience_required,
  requires_research, requires_publications, requires_community,
  targets_financial_need, targets_first_generation, targets_rural_origin,
  targets_ldc_countries, min_english_score, min_english_test_type
) VALUES (
  'schol-imperial-phd-2026',
  'imperial-college-presidents-phd-scholarships',
  'Imperial College President''s PhD Scholarships',
  'Imperial College London',
  'Imperial College London',
  '[]',
  '["PhD"]',
  '[]',
  'Full',
  'Full tuition fees, £26,500/yr stipend, £2,000/yr consumables fund',
  NULL,
  NULL,
  'Provides up to 50 research students the opportunity to work within their chosen research field with the support of an excellent supervisor. Expected to open October 2026.',
  'Must receive a first class or equivalent in an undergraduate or integrated Masters degree; or a distinction in a standalone Master''s qualification.',
  '["Transcripts", "Research proposal"]',
  'https://www.imperial.ac.uk/study/fees-and-funding/postgraduate-doctoral/grants-scholarships/presidents-phd/',
  'https://www.imperial.ac.uk/study/fees-and-funding/postgraduate-doctoral/grants-scholarships/presidents-phd/',
  true, true, now(), 'manual', 'pipeline',
  'Europe', '["UK"]'::jsonb, 'Opens Soon', 'University', 'Full Scholarships Opening Soon',
  false, false, false,
  'English', NULL,
  NULL, NULL, NULL,
  true, NULL, NULL,
  NULL, NULL, NULL,
  NULL, NULL, NULL
);

-- 11. Clarendon Fund Scholarships
INSERT INTO scholarships (
  id, name, provider, host_institution, countries, degree_levels,
  fields_of_study, funding_type, amount, deadline, opens_at,
  description, eligibility, required_documents, apply_url, source_url,
  published, verified, verified_at, verified_by, pipeline_source,
  host_region, host_country, urgency, sponsor_type, category,
  no_ielts, requires_leadership, is_intra_african,
  instruction_language, min_gpa_normalised,
  age_limit_masters, age_limit_phd, work_experience_required,
  requires_research, requires_publications, requires_community,
  targets_financial_need, targets_first_generation, targets_rural_origin,
  targets_ldc_countries, min_english_score, min_english_test_type
) VALUES (
  'schol-clarendon-2026',
  'clarendon-fund-scholarships',
  'Clarendon Fund Scholarships',
  'University of Oxford',
  'University of Oxford',
  '[]',
  '["Masters", "PhD"]',
  '[]',
  'Full',
  'Course fees in full and at least £20,780 annual grant for living expenses',
  NULL,
  NULL,
  'The Clarendon Fund is a major graduate scholarship scheme at the University of Oxford, offering fully-funded scholarships based on outstanding academic merit and potential. Automatic consideration upon applying for graduate study.',
  'Outstanding academic record (usually at least a first class honours degree or equivalent, e.g. GPA >= 3.7/4.0), future potential and aptitude, and student motivation.',
  '[]',
  'https://www.ox.ac.uk/admissions/graduate/fees-and-funding/funding/clarendon/applicants',
  'https://www.ox.ac.uk/admissions/graduate/fees-and-funding/funding/clarendon/applicants',
  true, true, now(), 'manual', 'pipeline',
  'Europe', '["UK"]'::jsonb, 'Opens Soon', 'University', 'Full Scholarships Opening Soon',
  false, false, false,
  'English', 0.925,
  NULL, NULL, NULL,
  NULL, NULL, NULL,
  NULL, NULL, NULL,
  NULL, NULL, NULL
);

-- 12. KAIST International Graduate Admission
INSERT INTO scholarships (
  id, name, provider, host_institution, countries, degree_levels,
  fields_of_study, funding_type, amount, deadline, opens_at,
  description, eligibility, required_documents, apply_url, source_url,
  published, verified, verified_at, verified_by, pipeline_source,
  host_region, host_country, urgency, sponsor_type, category,
  no_ielts, requires_leadership, is_intra_african,
  instruction_language, min_gpa_normalised,
  age_limit_masters, age_limit_phd, work_experience_required,
  requires_research, requires_publications, requires_community,
  targets_financial_need, targets_first_generation, targets_rural_origin,
  targets_ldc_countries, min_english_score, min_english_test_type
) VALUES (
  'schol-kaist-2026',
  'kaist-international-graduate-admission',
  'KAIST International Graduate Admission',
  'KAIST',
  'Korea Advanced Institute of Science and Technology',
  '[]',
  '["Masters", "PhD"]',
  '[]',
  'Full',
  'Tuition exemption, 300,000KRW/month allowance, national health insurance fee',
  NULL,
  NULL,
  'International graduate programs at KAIST offering full tuition exemption and living allowances for candidates demonstrating financial need and merit. English proficiency test waived for nationals of English-speaking African countries.',
  'Must hold a Bachelor''s degree (for Masters) or Master''s degree (for PhD). Neither parent can be a Korean citizen. English proficiency test required unless waived for English-speaking country nationals.',
  '["Curriculum vitae (CV)", "Recommendation letters", "Degree certificate and transcripts", "Proof of English proficiency"]',
  'https://apply.kaist.ac.kr/intergradapply',
  'https://nuclear.kaist.ac.kr/eng/informaiton/entrance.php',
  true, true, now(), 'manual', 'pipeline',
  'Asia', '["South Korea"]'::jsonb, 'Opens Soon', 'University', 'Full Scholarships Opening Soon',
  true, false, false,
  'English', NULL,
  NULL, NULL, NULL,
  NULL, NULL, NULL,
  true, NULL, NULL,
  NULL, 6.5, 'IELTS'
);

-- 13. Beit Trust Scholarships
INSERT INTO scholarships (
  id, name, provider, host_institution, countries, degree_levels,
  fields_of_study, funding_type, amount, deadline, opens_at,
  description, eligibility, required_documents, apply_url, source_url,
  published, verified, verified_at, verified_by, pipeline_source,
  host_region, host_country, urgency, sponsor_type, category,
  no_ielts, requires_leadership, is_intra_african,
  instruction_language, min_gpa_normalised,
  age_limit_masters, age_limit_phd, work_experience_required,
  requires_research, requires_publications, requires_community,
  targets_financial_need, targets_first_generation, targets_rural_origin,
  targets_ldc_countries, min_english_score, min_english_test_type
) VALUES (
  'schol-beit-2026',
  'beit-trust-scholarships',
  'Beit Trust Scholarships',
  'Beit Trust',
  'Partner Universities in UK and South Africa',
  '["Zambia", "Zimbabwe", "Malawi"]',
  '["Masters"]',
  '[]',
  'Full',
  'Full tuition, living allowance, UK Visa and Health Surcharge, flights, arrival/laptop/departure allowances',
  '2027-02-12',
  '2026-12-01',
  'Postgraduate scholarships for students from Zambia, Zimbabwe, and Malawi to study at partner universities in the UK or South Africa, focused on economic and social development.',
  'Must be nationals of and permanently resident in Zambia, Zimbabwe, or Malawi. Must intend to return to home country after studies. Work experience (at least 3 years) is highly valued.',
  '["Employer reference"]',
  'https://beittrust.org.uk/beit-trust-scholarships/',
  'https://beittrust.org.uk/beit-trust-scholarships/',
  true, true, now(), 'manual', 'pipeline',
  'Global', '["UK"]'::jsonb, 'Opens Soon', 'Foundation', 'Full Scholarships Opening Soon',
  false, false, true,
  'English', NULL,
  NULL, NULL, NULL,
  NULL, NULL, NULL,
  NULL, NULL, NULL,
  NULL, NULL, NULL
);
