-- ============================================================
-- SEED NEW SCHOLARSHIPS BY CATEGORY
-- ============================================================
-- Run this in Supabase SQL Editor to add all categorized scholarships.
-- Uses ON CONFLICT (id) DO NOTHING so existing records are safe.
-- IDs start at 'schol-100' to avoid collision with original seed data.
-- ============================================================

-- First, ensure the category column exists (safe to re-run)
ALTER TABLE scholarships ADD COLUMN IF NOT EXISTS category TEXT;

-- Add index on category for fast filtering (safe to re-run)
CREATE INDEX IF NOT EXISTS idx_scholarships_category ON scholarships(category);

-- ============================================================
-- CATEGORY 1: Full Scholarships Open Now (deadline ≤ 90 days)
-- Fully funded scholarships currently accepting applications
-- ============================================================

INSERT INTO scholarships (id, name, provider, host_institution, countries, degree_levels, fields_of_study, funding_type, amount, deadline, description, eligibility, required_documents, apply_url, source_url, published, verified, verified_at, view_count, no_ielts, instruction_language, host_region, host_country, iso2, category, is_intra_african) VALUES
(
  'schol-100',
  'Government of Czech Republic – Developing Countries Scholarship',
  'Czech Ministry of Education',
  'Czech Public Universities',
  '["Ethiopia", "Nigeria", "Rwanda", "Zambia"]',
  '["Bachelor", "Masters"]',
  '["All fields", "Engineering", "Science", "Economics"]',
  'Full',
  'Full tuition + monthly stipend + accommodation + health insurance',
  '2025-09-30',
  'The Government of the Czech Republic offers scholarships to students from developing countries to study at Czech public universities. The program covers the full cost of study including tuition, accommodation, living expenses, and health insurance. Fields are available across all disciplines offered by Czech universities.',
  'Citizens of eligible developing countries including Ethiopia, Nigeria, Rwanda, and Zambia. Must meet age and field restrictions depending on the track. Must not hold a scholarship from other Czech government programs.',
  '["CV / Resume", "Academic Transcript", "Motivation Letter", "Language Certificate", "Passport / ID"]',
  'https://www.msmt.gov.cz/eu-and-international-affairs/government-scholarships-developing-countries',
  'https://www.msmt.gov.cz/',
  true,
  false,
  '2026-06-10',
  15,
  false,
  'English',
  'Rest of Europe',
  '["czech republic"]',
  'CZ',
  'Full Scholarships Open Now',
  false
),
(
  'schol-101',
  'Pan African University (PAU) Scholarships',
  'African Union',
  'PAU Institutes (Algeria, Cameroon, Kenya, Nigeria, etc.)',
  '["Pan-African", "Kenya", "Nigeria", "Ghana", "South Africa", "Rwanda", "Uganda", "Ethiopia", "Tanzania", "Senegal", "Cameroon", "Algeria", "Zambia", "Zimbabwe"]',
  '["Masters", "PhD"]',
  '["Engineering", "Science", "Energy", "Water", "Space", "Governance", "Humanities"]',
  'Full',
  'Full tuition + monthly stipend + accommodation + travel + health insurance',
  '2025-12-15',
  'The Pan African University (PAU) is a network of five institutes hosted by different African countries. It offers full scholarships for Master''s and PhD programmes across strategic fields including science, engineering, energy, water, space science, governance, and humanities. The scholarship covers tuition, accommodation, living stipend, health insurance, and travel.',
  'Citizens of all African Union member states. Age limit varies by institute (typically max 28 for males, 30 for females for some tracks). Strong academic record and relevant bachelor''s degree for Master''s applicants.',
  '["CV / Resume", "Academic Transcript", "Motivation Letter", "Research Proposal", "Reference Letter", "Passport / ID"]',
  'https://www.au-pau.org/submission',
  'https://au.int/',
  true,
  false,
  '2026-06-10',
  35,
  false,
  'English',
  'Intra-African',
  '["multiple"]',
  '',
  'Full Scholarships Open Now',
  true
);

-- ============================================================
-- CATEGORY 2: Full Scholarships Opening in the Next 6 Months
-- ============================================================

INSERT INTO scholarships (id, name, provider, host_institution, countries, degree_levels, fields_of_study, funding_type, amount, deadline, description, eligibility, required_documents, apply_url, source_url, published, verified, verified_at, view_count, no_ielts, instruction_language, host_region, host_country, iso2, category, targets_financial_need, targets_first_generation, requires_leadership, requires_community) VALUES
(
  'schol-102',
  'Mastercard Foundation Scholars – University of Pretoria',
  'Mastercard Foundation & University of Pretoria',
  'University of Pretoria (South Africa)',
  '["Pan-African", "Kenya", "Nigeria", "Ghana", "South Africa", "Rwanda", "Uganda", "Ethiopia", "Tanzania", "Zambia", "Zimbabwe"]',
  '["Undergraduate", "Honours", "Masters"]',
  '["All fields", "Engineering", "Business", "Public Health", "Agriculture", "Education"]',
  'Full',
  'Full tuition + accommodation + living stipend + laptop + travel + medical aid',
  '2027-04-01',
  'The Mastercard Foundation Scholars Program at the University of Pretoria provides comprehensive scholarships to academically talented yet economically disadvantaged African students. The program covers undergraduate, Honours, and Master''s degrees with full financial support and leadership development.',
  'Citizens of Sub-Saharan African countries. Demonstrated academic excellence and leadership potential. Significant financial need. Commitment to return and contribute to Africa''s development.',
  '["CV / Resume", "Academic Transcript", "Motivation Letter", "Reference Letter", "Financial Need Statement"]',
  'https://www.up.ac.za/mastercard-foundation-scholars-program',
  'https://mastercardfdn.org/',
  true,
  false,
  '2026-06-10',
  25,
  false,
  'English',
  'Intra-African',
  '["south africa"]',
  'ZA',
  'Full Scholarships Opening Soon',
  true,
  true,
  true,
  true
),
(
  'schol-103',
  'Mastercard Foundation Scholars – Cambridge University',
  'Mastercard Foundation & University of Cambridge',
  'University of Cambridge (UK)',
  '["Pan-African", "Kenya", "Nigeria", "Ghana", "South Africa", "Rwanda", "Uganda", "Ethiopia", "Tanzania"]',
  '["Masters"]',
  '["All fields", "Engineering", "Computer Science", "Public Health", "Education", "Development Studies"]',
  'Full',
  'Full tuition + annual stipend + flights + visa + healthcare',
  '2026-12-01',
  'The Mastercard Foundation Scholars Program at Cambridge offers fully funded Master''s degrees to outstanding African students with leadership potential and financial need. Scholars receive comprehensive academic, financial, and social support throughout their studies.',
  'Citizens of Sub-Saharan African countries. Strong academic record (First Class or equivalent). Demonstrated leadership and commitment to social impact. Significant financial need.',
  '["CV / Resume", "Academic Transcript", "Motivation Letter", "Reference Letter", "Financial Need Statement", "Passport / ID"]',
  'https://www.mastercardfoundation.fund.cam.ac.uk',
  'https://mastercardfdn.org/',
  true,
  false,
  '2026-06-10',
  20,
  false,
  'English',
  'United Kingdom and Ireland',
  '["united kingdom"]',
  'GB',
  'Full Scholarships Opening Soon',
  true,
  true,
  true,
  true
),
(
  'schol-104',
  'Mastercard Foundation Scholars – African Leadership University',
  'Mastercard Foundation & ALU',
  'African Leadership University (Rwanda / Mauritius)',
  '["Pan-African", "Kenya", "Nigeria", "Ghana", "South Africa", "Rwanda", "Uganda", "Ethiopia", "Tanzania", "Senegal"]',
  '["Undergraduate"]',
  '["Business", "Computer Science", "Engineering", "Social Sciences", "International Relations"]',
  'Full',
  'Full tuition + accommodation + living stipend + laptop',
  '2026-11-15',
  'The Mastercard Foundation Scholars Program at African Leadership University (ALU) offers comprehensive undergraduate scholarships for talented African youth. ALU has campuses in Rwanda and Mauritius with a focus on entrepreneurial leadership and 21st-century skills.',
  'Citizens of Sub-Saharan African countries. Secondary school completion with strong grades. Demonstrated leadership potential. Financial need.',
  '["CV / Resume", "Academic Transcript", "Motivation Letter", "Reference Letter", "Financial Need Statement"]',
  'https://www.alueducation.com/mastercard-foundation-scholars-program-at-alu/',
  'https://mastercardfdn.org/',
  true,
  false,
  '2026-06-10',
  18,
  false,
  'English',
  'Intra-African',
  '["rwanda", "mauritius"]',
  '',
  'Full Scholarships Opening Soon',
  true,
  true,
  true,
  true
),
(
  'schol-105',
  'African STARS MSc Fellowships – Stellenbosch University',
  'Stellenbosch University',
  'Stellenbosch University (South Africa)',
  '["Pan-African", "Kenya", "Nigeria", "Ghana", "South Africa", "Rwanda", "Uganda", "Ethiopia", "Tanzania"]',
  '["Masters"]',
  '["Science", "Engineering", "Technology", "Mathematics", "Environmental Science"]',
  'Full',
  'Full tuition + monthly stipend + research costs + travel',
  '2026-08-01',
  'The African STARS (Science, Technology, and Academic Research Scholarship) Fellowships at Stellenbosch University provide full funding for African students to pursue MSc degrees. The program targets STEM fields and aims to build research capacity across Africa.',
  'Citizens of African countries. Strong academic background in STEM fields. Research experience preferred. Commitment to return to home country after studies.',
  '["CV / Resume", "Academic Transcript", "Research Proposal", "Reference Letter", "Motivation Letter"]',
  'https://scholarship-positions.com',
  'https://www.sun.ac.za/',
  true,
  false,
  '2026-06-10',
  12,
  false,
  'English',
  'Intra-African',
  '["south africa"]',
  'ZA',
  'Full Scholarships Opening Soon',
  false,
  false,
  false,
  false
);

-- ============================================================
-- CATEGORY 3: Partial Scholarships and Tuition Waivers
-- ============================================================

INSERT INTO scholarships (id, name, provider, host_institution, countries, degree_levels, fields_of_study, funding_type, amount, deadline, description, eligibility, required_documents, apply_url, source_url, published, verified, verified_at, view_count, no_ielts, instruction_language, host_region, host_country, iso2, category) VALUES
(
  'schol-106',
  'Open Doors Russian Scholarship',
  'Ministry of Science & Higher Education (Russia)',
  'Russian Universities',
  '["Pan-African", "Kenya", "Nigeria", "Ghana", "Ethiopia", "South Africa", "Uganda", "Tanzania", "Zambia"]',
  '["Masters", "PhD"]',
  '["All fields", "Engineering", "Computer Science", "Medicine", "Economics", "Humanities"]',
  'Partial',
  'Tuition-free study (no living stipend)',
  '2026-12-01',
  'The Open Doors Russian Scholarship is a Russian government initiative that offers tuition-free Master''s and PhD programs at top Russian universities. The scholarship covers full tuition costs but does not include a living stipend. Students need to cover accommodation and living expenses separately.',
  'Citizens of developing countries including multiple African states. Must pass the Open Doors Olympiad (online competition). No age limit. Bachelor''s degree required for Master''s track.',
  '["CV / Resume", "Academic Transcript", "Olympiad Application", "Passport / ID"]',
  'https://od.globaluni.ru/',
  'https://od.globaluni.ru/',
  true,
  false,
  '2026-06-10',
  10,
  true,
  'English',
  'Russia and CIS',
  '["russia"]',
  'RU',
  'Partial Scholarships & Tuition Waivers'
),
(
  'schol-107',
  'Reach Oxford Scholarship (Developing Countries)',
  'University of Oxford',
  'University of Oxford (UK)',
  '["Pan-African", "Kenya", "Nigeria", "Ghana", "South Africa", "Ethiopia", "Uganda", "Tanzania"]',
  '["Undergraduate"]',
  '["All fields"]',
  'Full',
  'Full tuition + living stipend + return flights',
  '2026-10-01',
  'The Reach Oxford Scholarship is a fully funded undergraduate scholarship for students from low-income and developing countries. It covers full tuition, living costs, and return flights. Only a small number of awards are made each year.',
  'Citizens of low-income/developing countries. Must apply and receive an offer from the University of Oxford for an undergraduate course. Demonstrated financial need.',
  '["CV / Resume", "Academic Transcript", "Motivation Letter", "Reference Letter", "Financial Need Statement"]',
  'https://www.ox.ac.uk/admissions/undergraduate/fees-and-funding/reach-oxford',
  'https://www.ox.ac.uk/',
  true,
  false,
  '2026-06-10',
  30,
  false,
  'English',
  'United Kingdom and Ireland',
  '["united kingdom"]',
  'GB',
  'Partial Scholarships & Tuition Waivers'
),
(
  'schol-108',
  'Regional Grants Italy (DSU Toscana, ADISU Puglia)',
  'Italian Regional Governments (DSU Toscana, ADISU Puglia)',
  'Italian Universities (Tuscany, Puglia regions)',
  '["Pan-African", "Kenya", "Nigeria", "Ghana", "Ethiopia", "South Africa", "Uganda", "Tanzania", "Senegal", "Cameroon"]',
  '["Bachelor", "Masters"]',
  '["All fields", "Engineering", "Arts", "Economics", "Science"]',
  'Partial',
  'Living support + housing + meals + partial tuition fees (need-based)',
  '2026-08-15',
  'Italian regional governments offer need-based scholarships for international students at universities in Tuscany (DSU Toscana) and Puglia (ADISU Puglia). Benefits include accommodation, meals, and partial fee waivers based on financial need.',
  'All non-EU students including Africans. Must enroll at a partner university in Tuscany or Puglia. Financial need documentation required. No IELTS required in many cases (MOI or other English proof accepted).',
  '["CV / Resume", "Academic Transcript", "Financial Need Statement", "Passport / ID", "Language Certificate"]',
  'https://www.dsu.toscana.it/',
  'https://www.dsu.toscana.it/',
  true,
  false,
  '2026-06-10',
  8,
  true,
  'English',
  'Italy and Mediterranean',
  '["italy"]',
  'IT',
  'Partial Scholarships & Tuition Waivers'
);

-- ============================================================
-- CATEGORY 4: Intra-African Scholarships
-- ============================================================

INSERT INTO scholarships (id, name, provider, host_institution, countries, degree_levels, fields_of_study, funding_type, amount, deadline, description, eligibility, required_documents, apply_url, source_url, published, verified, verified_at, view_count, no_ielts, instruction_language, host_region, host_country, iso2, category, is_intra_african) VALUES
(
  'schol-109',
  'Mastercard Foundation Scholars – African Universities (UP, Makerere, AUB)',
  'Mastercard Foundation',
  'Multiple African Universities (UP, Makerere, UCT, AUB, etc.)',
  '["Pan-African", "Kenya", "Nigeria", "Ghana", "South Africa", "Rwanda", "Uganda", "Ethiopia", "Tanzania"]',
  '["Undergraduate", "Masters", "PhD"]',
  '["All fields", "Engineering", "Business", "Public Health", "Agriculture", "Education"]',
  'Full',
  'Full cost of study + accommodation + living stipend + travel',
  '2026-12-31',
  'The Mastercard Foundation Scholars Program operates across multiple African universities including the University of Pretoria, Makerere University, University of Cape Town, and the African University of Botswana. Each offers full scholarships for African students with academic talent and financial need.',
  'African students (broadly defined). Demonstrated academic excellence. Financial need. Leadership potential. Commitment to giving back to the community.',
  '["CV / Resume", "Academic Transcript", "Motivation Letter", "Reference Letter", "Financial Need Statement"]',
  'https://mastercardfdn.org/en/what-we-do/our-programs/mastercard-foundation-scholars-program/where-to-apply/',
  'https://mastercardfdn.org/',
  true,
  false,
  '2026-06-10',
  22,
  false,
  'English',
  'Intra-African',
  '["multiple"]',
  '',
  'Intra-African Scholarships',
  true
),
(
  'schol-110',
  'University-Specific Bursaries (UCT, Makerere, Nairobi)',
  'Various African Universities',
  'University of Cape Town, Makerere University, University of Nairobi',
  '["South Africa", "Uganda", "Kenya"]',
  '["Undergraduate", "Masters"]',
  '["All fields", "Engineering", "Business", "Law", "Medicine", "Social Sciences"]',
  'Partial',
  'Varies by university (partial tuition, sometimes including accommodation)',
  '2026-10-01',
  'Many African universities offer their own bursaries and financial aid programs for local and regional students. These include need-based and merit-based awards at institutions like the University of Cape Town, Makerere University, and the University of Nairobi.',
  'Often limited to citizens of the host country or the region. Requires prior admission to the university. Financial need assessment required for need-based awards.',
  '["CV / Resume", "Academic Transcript", "Financial Need Statement", "Admission Letter"]',
  'https://www.uct.ac.za/students/financial-aid',
  'https://www.uct.ac.za/',
  true,
  false,
  '2026-06-10',
  5,
  false,
  'English',
  'Intra-African',
  '["south africa", "uganda", "kenya"]',
  '',
  'Intra-African Scholarships',
  true
);

-- ============================================================
-- CATEGORY 5: No IELTS Scholarships (MOI/Duolingo Accepted)
-- ============================================================

INSERT INTO scholarships (id, name, provider, host_institution, countries, degree_levels, fields_of_study, funding_type, amount, deadline, description, eligibility, required_documents, apply_url, source_url, published, verified, verified_at, view_count, no_ielts, instruction_language, host_region, host_country, iso2, category) VALUES
(
  'schol-111',
  'Türkiye Scholarships (Türkiye Bursları)',
  'Government of Türkiye',
  'Turkish Universities',
  '["Pan-African", "Kenya", "Nigeria", "Ghana", "South Africa", "Ethiopia", "Uganda", "Tanzania", "Senegal", "Cameroon", "Algeria", "Morocco", "Tunisia"]',
  '["Undergraduate", "Masters", "PhD"]',
  '["All fields", "Engineering", "Medicine", "Business", "International Relations", "Social Sciences", "Science"]',
  'Full',
  'Full tuition + monthly stipend + accommodation + health insurance + flights + Turkish language course',
  '2026-02-20',
  'Türkiye Scholarships is the Turkish government''s flagship scholarship program providing full funding for international students at all degree levels. It covers university tuition, monthly living allowance, accommodation, health insurance, flights, and a one-year Turkish language course.',
  'Citizens of all countries. Minimum academic achievement thresholds vary by level. No IELTS required — MOI, university language tests, or Turkish preparatory year accepted.',
  '["CV / Resume", "Academic Transcript", "Motivation Letter", "Reference Letter", "Passport / ID"]',
  'https://www.turkiyeburslari.gov.tr',
  'https://www.turkiyeburslari.gov.tr',
  true,
  false,
  '2026-06-10',
  45,
  true,
  'English',
  'Middle East and Turkey',
  '["turkey"]',
  'TR',
  'No IELTS Scholarships'
),
(
  'schol-112',
  'Chinese Government Scholarship (CSC)',
  'Chinese Ministry of Education (CSC)',
  'Chinese Universities',
  '["Pan-African", "Kenya", "Nigeria", "Ghana", "South Africa", "Ethiopia", "Uganda", "Tanzania", "Senegal", "Cameroon", "Zambia", "Zimbabwe"]',
  '["Undergraduate", "Masters", "PhD"]',
  '["All fields", "Engineering", "Computer Science", "Medicine", "Economics", "International Relations"]',
  'Full',
  'Full tuition + accommodation + monthly stipend + medical insurance',
  '2026-04-15',
  'The Chinese Government Scholarship (CSC) is a comprehensive funding program for international students to study at Chinese universities. It covers full tuition, accommodation, monthly living allowance, and comprehensive medical insurance.',
  'Citizens of countries with diplomatic relations with China. Good academic record. Age limits vary by level. HSK for Chinese-taught programs; many universities accept MOI for English-taught programs.',
  '["CV / Resume", "Academic Transcript", "Motivation Letter", "Reference Letter", "Passport / ID", "Study Plan"]',
  'https://www.campuschina.org',
  'https://www.campuschina.org',
  true,
  false,
  '2026-06-10',
  40,
  true,
  'English',
  'China and East Asia',
  '["china"]',
  'CN',
  'No IELTS Scholarships'
),
(
  'schol-113',
  'MEXT Scholarship',
  'Government of Japan (MEXT)',
  'Japanese Universities',
  '["Pan-African", "Kenya", "Nigeria", "Ghana", "South Africa", "Ethiopia", "Uganda", "Tanzania"]',
  '["Undergraduate", "Masters", "PhD"]',
  '["All fields", "Engineering", "Science", "Technology", "Social Sciences", "Humanities"]',
  'Full',
  'Full tuition + monthly stipend (~¥145,000) + accommodation + travel + health insurance',
  '2026-05-01',
  'The Japanese Government (MEXT) Scholarship offers full funding for international students to study at Japanese universities. It covers tuition, living expenses, accommodation, and round-trip airfare. The scholarship is offered through embassy recommendations and university recommendations.',
  'Citizens of countries with diplomatic relations with Japan. Age typically under 35. Strong academic record. Japanese language or internal tests accepted; IELTS often optional.',
  '["CV / Resume", "Academic Transcript", "Motivation Letter", "Reference Letter", "Passport / ID", "Study Plan"]',
  'https://www.mext.go.jp/en/policy/education/higher/title02/detail02/slist02-000003058.htm',
  'https://www.mext.go.jp',
  true,
  false,
  '2026-06-10',
  35,
  true,
  'English',
  'Japan and South Korea',
  '["japan"]',
  'JP',
  'No IELTS Scholarships'
),
(
  'schol-114',
  'Stipendium Hungaricum',
  'Government of Hungary (Tempus Public Foundation)',
  'Hungarian Universities',
  '["Pan-African", "Kenya", "Nigeria", "Ghana", "South Africa", "Ethiopia", "Uganda", "Tanzania", "Senegal", "Cameroon", "Algeria", "Morocco"]',
  '["Undergraduate", "Masters", "PhD"]',
  '["All fields", "Engineering", "Computer Science", "Medicine", "Economics", "Agriculture", "Social Sciences"]',
  'Full',
  'Full tuition + monthly stipend (HUF 43,700) + accommodation + health insurance',
  '2026-01-15',
  'Stipendium Hungaricum is the Hungarian government''s prestigious scholarship program for international students. It offers fully funded degree programs at Hungarian universities with full tuition coverage, monthly stipend, accommodation, and health insurance.',
  'Citizens of eligible partner countries (many African countries included). Good academic record. Age limits typically under 35. MOI or alternative English proof accepted at many host universities.',
  '["CV / Resume", "Academic Transcript", "Motivation Letter", "Reference Letter", "Passport / ID"]',
  'https://stipendiumhungaricum.hu',
  'https://stipendiumhungaricum.hu',
  true,
  false,
  '2026-06-10',
  38,
  true,
  'English',
  'Rest of Europe',
  '["hungary"]',
  'HU',
  'No IELTS Scholarships'
),
(
  'schol-115',
  'Romania Government Scholarship',
  'Government of Romania (MFA)',
  'Romanian Universities',
  '["Pan-African", "Kenya", "Nigeria", "Ghana", "Ethiopia", "South Africa", "Uganda", "Tanzania", "Senegal", "Cameroon"]',
  '["Undergraduate", "Masters", "PhD"]',
  '["All fields", "Engineering", "Medicine", "Economics", "Social Sciences", "Humanities"]',
  'Full',
  'Full tuition + monthly stipend + accommodation + health insurance',
  '2026-04-30',
  'The Romanian Government Scholarship offers full funding for international students to study at Romanian universities. The program covers tuition, accommodation, monthly living allowance, and health insurance. Scholarships are available for all degree levels.',
  'Citizens of non-EU countries including multiple African states. Must not hold Romanian citizenship. Good academic record. Usually no IELTS for Romanian-taught programs; internal language course available. Limited slots per country.',
  '["CV / Resume", "Academic Transcript", "Motivation Letter", "Reference Letter", "Passport / ID"]',
  'https://www.mae.ro/en/education',
  'https://www.mae.ro/',
  true,
  false,
  '2026-06-10',
  20,
  true,
  'English',
  'Rest of Europe',
  '["romania"]',
  'RO',
  'No IELTS Scholarships'
),
(
  'schol-116',
  'Taiwan ICDF Scholarship',
  'Taiwan ICDF',
  'Taiwanese Universities',
  '["Pan-African", "Kenya", "Nigeria", "Ghana", "South Africa", "Ethiopia", "Uganda", "Tanzania", "Senegal"]',
  '["Undergraduate", "Masters", "PhD"]',
  '["All fields", "Engineering", "Agriculture", "Public Health", "Economics", "International Relations"]',
  'Full',
  'Full tuition + accommodation + monthly stipend + return flights + health insurance',
  '2026-03-15',
  'The Taiwan ICDF Scholarship provides full funding for students from partner developing countries to study at Taiwanese universities. The program covers tuition, accommodation, living expenses, round-trip airfare, and health insurance.',
  'Citizens of countries on Taiwan ICDF''s partner list. Strong academic record. Age under 35 for Master''s and 40 for PhD. Alternatives to IELTS accepted depending on university; MOI often accepted.',
  '["CV / Resume", "Academic Transcript", "Motivation Letter", "Reference Letter", "Study Plan"]',
  'https://www.icdf.org.tw',
  'https://www.icdf.org.tw',
  true,
  false,
  '2026-06-10',
  15,
  true,
  'English',
  'China and East Asia',
  '["taiwan"]',
  'TW',
  'No IELTS Scholarships'
),
(
  'schol-117',
  'Brunei Darussalam Government Scholarship',
  'Government of Brunei Darussalam',
  'Universities in Brunei Darussalam',
  '["Pan-African", "Kenya", "Nigeria", "Ghana", "South Africa", "Ethiopia", "Uganda", "Tanzania"]',
  '["Undergraduate", "Masters"]',
  '["All fields", "Engineering", "Business", "Science", "Social Sciences", "Humanities"]',
  'Full',
  'Full tuition + monthly stipend + accommodation + return flights + health insurance',
  '2026-03-31',
  'The Brunei Darussalam Government Scholarship offers full funding for international students to pursue undergraduate and Master''s degrees in Brunei. The scholarship covers full tuition, accommodation, living expenses, round-trip airfare, and health insurance.',
  'Citizens of countries with diplomatic relations with Brunei. Good academic record. Age under 25 for undergraduate and 35 for Master''s. MOI or internal English tests accepted at some institutions.',
  '["CV / Resume", "Academic Transcript", "Motivation Letter", "Reference Letter", "Passport / ID"]',
  'https://www.mfa.gov.bn/',
  'https://www.mfa.gov.bn/',
  true,
  false,
  '2026-06-10',
  8,
  true,
  'English',
  'Southeast Asia and Oceania',
  '["brunei"]',
  'BN',
  'No IELTS Scholarships'
);

-- ============================================================
-- CATEGORY 6: Undergraduate Scholarships
-- ============================================================

INSERT INTO scholarships (id, name, provider, host_institution, countries, degree_levels, fields_of_study, funding_type, amount, deadline, description, eligibility, required_documents, apply_url, source_url, published, verified, verified_at, view_count, no_ielts, instruction_language, host_region, host_country, iso2, category) VALUES
(
  'schol-118',
  'Türkiye Scholarships – Undergraduate',
  'Government of Türkiye',
  'Turkish Universities',
  '["Pan-African", "Kenya", "Nigeria", "Ghana", "South Africa", "Ethiopia", "Uganda", "Tanzania", "Senegal"]',
  '["Undergraduate"]',
  '["All fields", "Engineering", "Medicine", "Business", "International Relations", "Social Sciences"]',
  'Full',
  'Full tuition + monthly stipend (TRY 3,500) + accommodation + health insurance + flights + Turkish language course',
  '2026-02-20',
  'Türkiye Scholarships undergraduate track provides full funding for international students to pursue bachelor''s degrees at Turkish universities at no cost. The comprehensive package covers all academic and living expenses.',
  'Citizens of all countries. Minimum 70% academic average. Age under 21. No IELTS accepted — MOI or Turkish language preparatory year available.',
  '["CV / Resume", "Academic Transcript", "Motivation Letter", "Passport / ID"]',
  'https://www.turkiyeburslari.gov.tr',
  'https://www.turkiyeburslari.gov.tr',
  true,
  false,
  '2026-06-10',
  30,
  true,
  'English',
  'Middle East and Turkey',
  '["turkey"]',
  'TR',
  'Undergraduate Scholarships'
),
(
  'schol-119',
  'Chinese Government Scholarship – Undergraduate',
  'Chinese Ministry of Education (CSC)',
  'Chinese Universities',
  '["Pan-African", "Kenya", "Nigeria", "Ghana", "South Africa", "Ethiopia", "Uganda", "Tanzania"]',
  '["Undergraduate"]',
  '["All fields", "Engineering", "Computer Science", "Medicine", "Economics"]',
  'Full',
  'Full tuition + accommodation + monthly stipend (CNY 2,500) + medical insurance',
  '2026-04-15',
  'The Chinese Government Scholarship undergraduate track provides full funding for bachelor''s degree studies at Chinese universities. The scholarship covers all academic and living costs for the full duration of the program.',
  'Citizens of countries with diplomatic relations with China. High school diploma with strong grades. Age under 25. HSK for Chinese-taught programs; MOI accepted for English-taught programs.',
  '["CV / Resume", "Academic Transcript", "Motivation Letter", "Reference Letter", "Passport / ID"]',
  'https://www.campuschina.org',
  'https://www.campuschina.org',
  true,
  false,
  '2026-06-10',
  25,
  true,
  'English',
  'China and East Asia',
  '["china"]',
  'CN',
  'Undergraduate Scholarships'
),
(
  'schol-120',
  'MEXT Undergraduate Scholarship',
  'Government of Japan (MEXT)',
  'Japanese Universities',
  '["Pan-African", "Kenya", "Nigeria", "Ghana", "South Africa", "Ethiopia", "Uganda", "Tanzania"]',
  '["Undergraduate"]',
  '["All fields", "Engineering", "Science", "Technology", "Social Sciences", "Humanities"]',
  'Full',
  'Full tuition + monthly stipend (~¥145,000) + accommodation + travel + health insurance',
  '2026-05-01',
  'The MEXT Undergraduate Scholarship offers full funding for international students to pursue bachelor''s degrees at Japanese universities. The scholarship is offered through embassy recommendations with a separate application track for undergraduate applicants.',
  'Citizens of countries with diplomatic relations with Japan. Completed secondary education. Age under 25. Japanese language or internal tests accepted; IELTS often optional.',
  '["CV / Resume", "Academic Transcript", "Motivation Letter", "Reference Letter", "Passport / ID"]',
  'https://www.mext.go.jp',
  'https://www.mext.go.jp',
  true,
  false,
  '2026-06-10',
  20,
  true,
  'English',
  'Japan and South Korea',
  '["japan"]',
  'JP',
  'Undergraduate Scholarships'
),
(
  'schol-121',
  'Stipendium Hungaricum – Bachelor''s',
  'Tempus Public Foundation (Hungary)',
  'Hungarian Universities',
  '["Pan-African", "Kenya", "Nigeria", "Ghana", "South Africa", "Ethiopia", "Uganda", "Tanzania", "Senegal"]',
  '["Undergraduate"]',
  '["All fields", "Engineering", "Computer Science", "Medicine", "Economics", "Agriculture"]',
  'Full',
  'Full tuition + monthly stipend (HUF 43,700) + accommodation + health insurance',
  '2026-01-15',
  'Stipendium Hungaricum offers full funding for undergraduate studies at Hungarian universities. The program provides comprehensive financial support including tuition, living expenses, accommodation, and health insurance.',
  'Citizens of eligible partner countries (many African countries included). Secondary school completion with good grades. Age typically under 25. MOI or alternative English proof accepted.',
  '["CV / Resume", "Academic Transcript", "Motivation Letter", "Reference Letter", "Passport / ID"]',
  'https://stipendiumhungaricum.hu',
  'https://stipendiumhungaricum.hu',
  true,
  false,
  '2026-06-10',
  28,
  true,
  'English',
  'Rest of Europe',
  '["hungary"]',
  'HU',
  'Undergraduate Scholarships'
);

-- ============================================================
-- CATEGORY 7: Corporate and Foundation Scholarships
-- ============================================================

INSERT INTO scholarships (id, name, provider, host_institution, countries, degree_levels, fields_of_study, funding_type, amount, deadline, description, eligibility, required_documents, apply_url, source_url, published, verified, verified_at, view_count, no_ielts, instruction_language, host_region, host_country, category) VALUES
(
  'schol-122',
  'Google PhD Fellowship (Africa)',
  'Google',
  'Global (host universities worldwide)',
  '["Pan-African", "Kenya", "Nigeria", "Ghana", "South Africa", "Ethiopia", "Uganda", "Tanzania", "Rwanda"]',
  '["PhD"]',
  '["Computer Science", "Data Science", "Machine Learning", "AI", "Software Engineering", "Computational Neuroscience"]',
  'Partial',
  'Tuition + stipend support + research expenses + Google mentorship',
  '2026-09-01',
  'The Google PhD Fellowship (Africa) supports outstanding PhD candidates in Computer Science and related fields who are pursuing research at African universities. Fellows receive financial support, Google mentorship, and networking opportunities with Google researchers.',
  'Enrolled or admitted to a PhD program at an African university. Focus on Computer Science or related fields. Strong research proposal. Good academic record.',
  '["CV / Resume", "Academic Transcript", "Research Proposal", "Reference Letter", "Publication List"]',
  'https://research.google/outreach/phd-fellowship/',
  'https://research.google/',
  true,
  false,
  '2026-06-10',
  15,
  false,
  'English',
  'Global',
  '["multiple"]',
  'Corporate & Foundation Scholarships'
),
(
  'schol-123',
  'Generation Google Scholarship – EMEA',
  'Google',
  'EMEA Universities',
  '["Pan-African", "Kenya", "Nigeria", "Ghana", "South Africa", "Ethiopia", "Uganda", "Tanzania", "Senegal", "Cameroon"]',
  '["Undergraduate", "Masters"]',
  '["Computer Science", "Software Engineering", "Data Science", "Information Technology", "Mathematics"]',
  'Partial',
  '7,000 EUR one-time award (tuition support)',
  '2026-04-01',
  'The Generation Google Scholarship (EMEA) supports women in Computer Science and related fields from Africa, Europe, and the Middle East. The scholarship provides financial support plus a retreat and networking opportunities.',
  'Female students enrolled in CS or related programs at EMEA universities. Strong academic record. Demonstrated leadership and passion for technology.',
  '["CV / Resume", "Academic Transcript", "Motivation Letter", "Reference Letter"]',
  'https://www.google.com/scholarships/generation-google-scholarship/',
  'https://www.google.com/',
  true,
  false,
  '2026-06-10',
  12,
  false,
  'English',
  'Global',
  '["multiple"]',
  'Corporate & Foundation Scholarships'
),
(
  'schol-124',
  'Aga Khan Foundation International Scholarship',
  'Aga Khan Foundation',
  'Multiple Countries',
  '["Kenya", "Uganda", "Tanzania", "Mozambique", "Madagascar", "India", "Pakistan", "Afghanistan", "Syria", "Egypt"]',
  '["Masters", "PhD"]',
  '["All fields", "Engineering", "Medicine", "Education", "Agriculture", "Social Sciences"]',
  'Full',
  'Tuition + living expenses (often 50% grant / 50% loan)',
  '2026-03-31',
  'The Aga Khan Foundation International Scholarship provides a limited number of scholarships per year for postgraduate studies to outstanding students from developing countries. The scholarship is a mix of grant and loan, aiming to support students who have no other means of financing their studies.',
  'Citizens of specific eligible countries including Kenya, Uganda, Tanzania, Mozambique, and Madagascar. Excellent academic records. Admission to a reputable institution. Demonstrated financial need.',
  '["CV / Resume", "Academic Transcript", "Motivation Letter", "Reference Letter", "Financial Need Statement", "Admission Letter"]',
  'https://www.akdn.org/our-agencies/aga-khan-foundation',
  'https://www.akdn.org/',
  true,
  false,
  '2026-06-10',
  18,
  false,
  'English',
  'Global',
  '["multiple"]',
  'Corporate & Foundation Scholarships'
),
(
  'schol-125',
  'Mo Ibrahim Foundation Scholarships (LSE, SOAS)',
  'Mo Ibrahim Foundation',
  'LSE, SOAS (UK)',
  '["Pan-African", "Kenya", "Nigeria", "Ghana", "South Africa", "Ethiopia", "Uganda", "Tanzania", "Senegal"]',
  '["Masters"]',
  '["Governance", "Public Policy", "International Relations", "Development Studies", "Law"]',
  'Full',
  'Full tuition + living stipend + mentoring + internship',
  '2026-05-15',
  'The Mo Ibrahim Foundation offers scholarships for African students to study governance and related fields at top UK universities including LSE and SOAS. The program includes full financial support, mentoring, and internship opportunities at the foundation.',
  'African citizens. Strong academic record in a relevant field. Demonstrated commitment to African governance and development. Admission to the partner university program.',
  '["CV / Resume", "Academic Transcript", "Motivation Letter", "Reference Letter", "Admission Letter"]',
  'https://mo.ibrahim.foundation/',
  'https://mo.ibrahim.foundation/',
  true,
  false,
  '2026-06-10',
  14,
  false,
  'English',
  'United Kingdom and Ireland',
  '["united kingdom"]',
  'Corporate & Foundation Scholarships'
),
(
  'schol-126',
  'Tony Elumelu Foundation Entrepreneurship Programme',
  'Tony Elumelu Foundation (TEF)',
  'Africa-wide (online + in-person)',
  '["Pan-African", "Kenya", "Nigeria", "Ghana", "South Africa", "Rwanda", "Uganda", "Ethiopia", "Tanzania", "Senegal", "Cameroon", "Algeria"]',
  '["Not Applicable"]',
  '["Business", "Entrepreneurship", "Agribusiness", "Technology", "Creative Industries"]',
  'Partial',
  'Seed funding ($5,000) + mentorship + training (not academic tuition)',
  '2026-03-01',
  'The Tony Elumelu Foundation Entrepreneurship Programme is a leading African philanthropic initiative empowering young African entrepreneurs. It provides seed capital, mentorship, and business training to early-stage startup founders across all 54 African countries.',
  'African entrepreneurs aged 18 and above with a viable business idea. Must be a citizen of an African country. Business must be for-profit and at an early stage.',
  '["Business Plan", "CV / Resume", "Identification Document"]',
  'https://www.tonyelumelufoundation.org/entrepreneurship-programme',
  'https://www.tonyelumelufoundation.org/',
  true,
  false,
  '2026-06-10',
  25,
  false,
  'English',
  'Intra-African',
  '["multiple"]',
  'Corporate & Foundation Scholarships'
);

-- Fix broken quoting in schol-124
UPDATE scholarships SET countries = '["Kenya", "Uganda", "Tanzania", "Mozambique", "Madagascar", "India", "Pakistan", "Afghanistan", "Syria", "Egypt"]' WHERE id = 'schol-124';

-- ============================================================
-- CATEGORY 8: Francophone and Lusophone Scholarships
-- ============================================================

INSERT INTO scholarships (id, name, provider, host_institution, countries, degree_levels, fields_of_study, funding_type, amount, deadline, description, eligibility, required_documents, apply_url, source_url, published, verified, verified_at, view_count, no_ielts, instruction_language, host_region, host_country, iso2, category) VALUES
(
  'schol-127',
  'French Government / Campus France Scholarships (Eiffel)',
  'French Ministry via Campus France',
  'French Universities',
  '["Pan-African", "Senegal", "Cameroon", "Algeria", "Morocco", "Tunisia", "Kenya", "Nigeria", "Ghana", "Ethiopia"]',
  '["Masters", "PhD"]',
  '["All fields", "Engineering", "Science", "Economics", "Law", "Political Science", "Humanities"]',
  'Full',
  'Tuition (up to €12,000/year for Master''s) + monthly stipend (€1,181) + travel + health insurance + housing allowance',
  '2026-12-10',
  'The French Government through Campus France offers various scholarships for international students to study at French universities. The Eiffel Excellence Scholarship is the flagship program for top international candidates in engineering, science, economics, law, and political science.',
  'Non-French nationality. Age up to 25 for Master''s (Eiffel), up to 30 for PhD. Strong academic record. Applications must be submitted by the French host institution.',
  '["CV / Resume", "Academic Transcript", "Motivation Letter", "Reference Letter", "Language Certificate"]',
  'https://www.campusfrance.org/en/eiffel-scholarship-program-of-excellence',
  'https://www.campusfrance.org/',
  true,
  false,
  '2026-06-10',
  22,
  false,
  'French',
  'France and Belgium',
  '["france"]',
  'FR',
  'Francophone & Lusophone Scholarships'
),
(
  'schol-128',
  'Government of Portugal Scholarships for CPLP / Lusophone',
  'Government of Portugal',
  'Portuguese Universities',
  '["Pan-African", "Mozambique", "Angola", "Cape Verde", "Guinea-Bissau", "Sao Tome and Principe", "Equatorial Guinea", "Senegal", "Kenya", "Nigeria"]',
  '["Undergraduate", "Masters", "PhD"]',
  '["All fields", "Engineering", "Medicine", "Economics", "Social Sciences", "Humanities"]',
  'Partial',
  'Mix of tuition waivers and stipends depending on program',
  '2026-05-31',
  'The Portuguese Government offers scholarships for students from CPLP (Community of Portuguese Language Countries) and other developing countries to study at Portuguese universities. Programs cover various fields with different levels of financial support.',
  'Citizens of CPLP member states (especially Lusophone African countries) and other developing countries. Portuguese language proficiency typically required. Good academic record.',
  '["CV / Resume", "Academic Transcript", "Motivation Letter", "Language Certificate", "Passport / ID"]',
  'https://www.dges.gov.pt/',
  'https://www.dges.gov.pt/',
  true,
  false,
  '2026-06-10',
  10,
  false,
  'Portuguese',
  'Italy and Mediterranean',
  '["portugal"]',
  'PT',
  'Francophone & Lusophone Scholarships'
),
(
  'schol-129',
  'Brazil University Scholarships for International Students',
  'Brazilian Public Universities',
  'Brazilian Public Universities',
  '["Pan-African", "Mozambique", "Angola", "Cape Verde", "Senegal", "Kenya", "Nigeria", "Ghana", "South Africa"]',
  '["Undergraduate", "Masters"]',
  '["All fields", "Engineering", "Medicine", "Agriculture", "Social Sciences"]',
  'Partial',
  'Tuition-free study (limited stipends available through university programs)',
  '2026-09-01',
  'Brazilian public universities offer tuition-free education for all students including international applicants. Additional scholarship programs may provide limited stipends for living costs. Many universities have programs targeting Lusophone African students through bilateral agreements.',
  'International students including Africans applying to Brazilian public universities. Some programs target Lusophone Africa. Portuguese language proficiency required. Varies by university program.',
  '["CV / Resume", "Academic Transcript", "Motivation Letter", "Language Certificate", "Passport / ID"]',
  'https://www.gov.br/mec/',
  'https://www.gov.br/',
  true,
  false,
  '2026-06-10',
  8,
  false,
  'Portuguese',
  'South America',
  '["brazil"]',
  'BR',
  'Francophone & Lusophone Scholarships'
);

-- Fix broken quoting in schol-127, schol-128, schol-129
UPDATE scholarships SET fields_of_study = '["All fields", "Engineering", "Science", "Economics", "Law", "Political Science", "Humanities"]' WHERE id = 'schol-127';
UPDATE scholarships SET countries = '["Pan-African", "Mozambique", "Angola", "Cape Verde", "Guinea-Bissau", "Sao Tome and Principe", "Equatorial Guinea", "Senegal", "Kenya", "Nigeria"]' WHERE id = 'schol-128';
UPDATE scholarships SET countries = '["Pan-African", "Mozambique", "Angola", "Cape Verde", "Senegal", "Kenya", "Nigeria", "Ghana", "South Africa"]' WHERE id = 'schol-129';
